- id: doi:10.2514/1.G009119
  
- id: doi:10.2514/6.2026-0110

- id: doi:10.23919/ACC63710.2025.11108101

- id: doi:10.1109/TASE.2025.3574289

- id: doi:10.2514/1.G008324

- title: "Game-theoretic sensor tasking for satellite constellation control with computational scalability and performance guarantees"
  authors:
    - "Donghae Kim"
    - "Yoonjae Lee"
    - "Andrew J. Miller"
    - "Maruthi R. Akella"
  publisher: "75th International Astronautical Congress (IAC)"
  date: '2024-10-18'
  type: paper
  raw: true

- id: doi:10.23919/ACC60939.2024.10644208

- id: doi:10.2514/1.G001739

- title: "Spin entry analysis based on bifurcation analysis and recovery controller design"
  authors:
    - "Donghae Kim"
    - "Gyeongtaek Oh"
    - "Yongjun Seo"
    - "Youdan Kim"
  publisher: "7th Asia-Pacific International Symposium on Aerospace Technology Conference (APISAT)"
  date: '2015-11-27'
  type: paper
  raw: true

- title: "Dilemma-Free Pursuer Routing for Target Defense"
  authors:
  - Yoonjae Lee
  - Donghae Kim
  - Efstathios Bakolas
  publisher: Manuscript in preparation
  date: '2026-12-31'
  type: paper
  raw: true

- title: Trust-based Task Auction with Untruthful Agents
  authors:
  - Donghae Kim
  - Maruthi R. Akella
  publisher: Manuscript in preparation
  date: '2026-12-31'
  type: paper
  raw: true

- title: Multilateral Task Negotiation Based on Trust
  authors:
  - Donghae Kim
  - Maruthi R. Akella
  publisher: Under review
  date: '2026-12-31'
  type: paper
  raw: true
